export const WS_CONNECTION_FEED_START: 'WS_CONNECTION_FEED_START' = 'WS_CONNECTION_FEED_START';
export const WS_CONNECTION_FEED_SUCCESS: 'WS_CONNECTION_FEED_SUCCESS' = 'WS_CONNECTION_FEED_SUCCESS';
export const WS_GET_MESSAGE_FEED: 'WS_GET_MESSAGE_FEED' = 'WS_GET_MESSAGE_FEED';
export const WS_CONNECTION_FEED_ERROR: 'WS_CONNECTION_FEED_ERROR' = 'WS_CONNECTION_FEED_ERROR';
export const WS_CONNECTION_FEED_CLOSED: 'WS_CONNECTION_FEED_CLOSED' = 'WS_CONNECTION_FEED_CLOSED';

export const WS_CONNECTION_PROFILE_ORDERS_START: 'WS_CONNECTION_PROFILE_ORDERS_START' = 'WS_CONNECTION_PROFILE_ORDERS_START';
export const WS_CONNECTION_PROFILE_ORDERS_SUCCESS: 'WS_CONNECTION_PROFILE_ORDERS_SUCCESS' = 'WS_CONNECTION_PROFILE_ORDERS_SUCCESS';
export const WS_GET_MESSAGE_PROFILE_ORDERS: 'WS_GET_MESSAGE_PROFILE_ORDERS' = 'WS_GET_MESSAGE_PROFILE_ORDERS';
export const WS_CONNECTION_PROFILE_ORDERS_ERROR: 'WS_CONNECTION_PROFILE_ORDERS_ERROR' = 'WS_CONNECTION_PROFILE_ORDERS_ERROR';
export const WS_CONNECTION_PROFILE_ORDERS_CLOSED: 'WS_CONNECTION_PROFILE_ORDERS_CLOSED' = 'WS_CONNECTION_PROFILE_ORDERS_CLOSED';
